### ISSUE TITLE
Docker image running, but how do I call functions?

### ISSUE THREAD

**Issue by marvinm2** [quanted/OPERAWS#3]
Hi! I tried the Dockerfile to create a Docker image, run that with port 3344 exposed, and tried http://localhost:3344/opera/test in the browser, which gave me 

```
{
  "status": "opera_flask up and running."
}
```

However, I don't know how I can not use the functionalities of opera. Is there some documentation available on this?

**Comment by popenc** [comment]
Hey @marvinm2, thanks for your interest in the repo! I have yet to add documentation for this, but the endpoints can be found in OPERAWS/opera_flask.py. It's really just two endpoints, the test one and a POST request laid out below for executing OPERA.

You should be able to make requests to OPERA with the following URL and POST request as an example:

```
URL: http://localhost:3344/opera/rest/run
POST: {"smiles": "c1ccccc1"}
```

Let me know if that works for you.
